export const REQUIRED_APP_ENVIRONMENT_VARIABLES = [
  "NEXT_PUBLIC_SUPABASE_URL",
  "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
] as const;

export const RECOMMENDED_APP_ENVIRONMENT_VARIABLES = [
  "APP_URL",
  "FLUTTERWAVE_PUBLIC_KEY",
  "FLUTTERWAVE_SECRET_KEY",
  "FLUTTERWAVE_SECRET_HASH",
  "AFRICASTALKING_USERNAME",
  "AFRICASTALKING_API_KEY",
  "AFRICASTALKING_SENDER_ID",
  "RESEND_API_KEY",
  "RESEND_FROM_EMAIL",
] as const;

export const REQUIRED_SUPABASE_EDGE_FUNCTION_SECRETS = [
  "SUPABASE_URL",
  "SUPABASE_SERVICE_ROLE_KEY",
  "APP_URL",
  "AFRICASTALKING_USERNAME",
  "AFRICASTALKING_API_KEY",
  "AFRICASTALKING_SENDER_ID",
  "RESEND_API_KEY",
  "RESEND_FROM_EMAIL",
] as const;
